### ISSUE TITLE
ImportError: cannot import name 'XMLSchemaProxy' from 'elementpath'

### ISSUE THREAD

**Issue by alexandrebrilhante** [blackrock/xml_to_json#1]
In Python 3.7.8:

```bash
python xml_to_json.py ./foo.xml
```

returns `ImportError: cannot import name 'XMLSchemaProxy' from 'elementpath'`.

**Comment by chunheisiu** [comment]
I got this error as well.
Try a workaround by installing `elementpath==1.0.12`. Seems like there are some breaking changes in `elementpath` between version 1 and 2.

**Comment by Montana** [comment]
Sounds like you have circular dependent imports. In other words, `xml_to_json.py` is imported from the `ParqConverter` class before the class the other classes that need to be defined are actually defined. Secondarily, `xml_to_json` tries to import `ParqConverter`, which is already initializing. Remove the dependency to `xml_to_json` from the module completely.
